
spring:
  jpa:
    hibernate:
      ddl-auto=none
  datasource:
    url: jdbc:mysql://localhost:3306/ride-service
    username: root
    driver-class: com.mysql.jdbc.Driver
#   flyway:
#     url: jdbc:mysql://localhost:3306/ride-service
#     username: root
#     baselineOnMigrate: true
